### ISSUE TITLE
License mismatch on fonts.google.com versus here.

### ISSUE THREAD

**Issue by Voperak** [googlefonts/opensans#35]
I noticed that the current license, "SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007", states that any redistribution of Open Sans must have the same license. However, Google lists the license as "Apache License, Version 2.0" on its website.

[https://fonts.google.com/specimen/Open+Sans#license](https://fonts.google.com/specimen/Open+Sans#license)

Which would be the appropriate license to include in my usage of Open Sans?

**Comment by davelab6** [comment]
It depends which version of the font you obtained. If you get the older version of the project that is under Apache, use Apache. If you get the newer version of the project that is under OFL, use OFL.
