### ISSUE TITLE
Alternative design for lowercase l (to better distinguish it from uppercase i)

### ISSUE THREAD

**Issue by paperboyo** [googlefonts/opensans#56]
Thank you ever so much for all your work! We [recently](https://github.com/guardian/grid/pull/3893) started using Open Sans, but I can’t seem to find an alternative `l` design that will make eg. this more readable:

![image](https://user-images.githubusercontent.com/6032869/204616217-d544ca8a-b843-4fbc-9017-f0278c9037ba.png)

Would be great to be able to switch to it via CSS (if not have it as default). Or is this really a feature request for Noto Sans?

**Comment by kenmcd** [comment]
Use Stylistic Set 1 (`ss01`) 
or Stylistic Set 3 (`ss03`)
or Stylistic Alternates (`salt`)
for an alternate uppercase I.

![2022-11-29_16-04-21](https://user-images.githubusercontent.com/844920/204675752-359caee2-9976-4cf3-a5a7-c077ac14c219.gif)

**Comment by paperboyo** [comment]
Thanks. I would rather have an `l` with a pronounced terminal, but that may be an aesthetic choice (somehow I feel I could use it in the whole app as less intrusive, instead of targetting weirder – almost serif – `I` to odd places).

But the thing is, possibly because of https://github.com/google/fonts/issues/1335, I have no access to alternates at all the way I’ve done it. I will keep this issue open in case anyone has an opinion on a design of `l` (or, indeed, if someone would kindly point out that I’m being dumb and there is a way to ask Google Fonts API to include certain OpenType features). But feel free to close it or I will if no movement.

Thanks again.

**Comment by kenmcd** [comment]
Currently you cannot use stylistic sets with the web fonts.

Noto Sans is nearly identical, and it defaults to the alternate uppercase I. The weight is slightly different, but you could use the variable font if that is an issue.
![NotoSans](https://user-images.githubusercontent.com/844920/204889095-6f67ca60-4a00-4281-97c1-152a98dedb83.png)

**Comment by paperboyo** [comment]
Thanks!
Not being able to use OT features with Fonts API, while serious, is a dup. And alternative design for `l` sounds like it might be an issue for Noto (and a long shot, probably). So… closing.
